DROP TABLE if EXISTS replies;
DROP TABLE if EXISTS threads;

CREATE TABLE threads (
  id SERIAL PRIMARY KEY,
  subject TEXT
);

CREATE TABLE replies (
  id SERIAL PRIMARY KEY,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  thread_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  text TEXT NOT NULL,
  FOREIGN KEY (thread_id) REFERENCES threads (id)
);
